spring.application.name=COMP303_Assignment4_Manager

server.port=8084
 
#In the interest of security, connect to your own mongoDB instance and do not commit sensitive changes to this file
spring.mongodb.uri=mongodb://localhost:27017/assignment4
 
spring.mongodb.port=27017
 
spring.mongodb.database=assignment4

eureka.client.serviceUrl.defaultZone = http://localhost:8080/eureka
